export const STABLECOIN_IDS: Record<string, string> = {
    'USDT': 'tether',
    'USDC': 'usd-coin',
    'DAI': 'dai',
    'BUSD': 'binance-usd',
    'RLUSD': 'ripple-usd',
    // 'FRAX': 'frax',
    // 'TUSD': 'true-usd',
    // 'USDD': 'usdd',
    // 'LUSD': 'liquity-usd',
    // 'GUSD': 'gemini-dollar',
    // 'USDP': 'paxos-standard',
    // 'SUSD': 'nusd',
    // 'FRXETH': 'frax-ether',
    // 'MIM': 'magic-internet-money',
    // 'DOLA': 'dola-usd',
};

export const PLATFORM_TO_CHAIN_ID: Record<string, number> = {
    'ethereum': 1,
    'binance-smart-chain': 56,
    'polygon-pos': 137,
    'arbitrum-one': 42161,
    'optimistic-ethereum': 10,
    'avalanche': 43114,
    'fantom': 250,
    'klay-token': 8217,
    'kava': 2222,
    'celo': 42220,
    'base': 8453,
    'cronos': 25,
    'moonbeam': 1284,
    'moonriver': 1285,
    'harmony-shard-0': 1666600000,
    'aurora': 1313161554,
};